### ISSUE TITLE
Create About Us page

### ISSUE THREAD

**Issue by Enotmd** [web-seven/website#38]
## Issue summary:
Required to create About Us page :

![image](https://github.com/web-seven/website/assets/109219657/b3fd3a87-17b2-44b3-8b3b-1aef14033d23)

## Issue details:
Need the page and the components  for the coming Our team and Careers Pages.

## References:
 - Link to page with HTML for this component: in your local downloaded MARTEX/HTML/about.html

**Comment by web7evgheni** [comment]
@Enotmd why it looks so strange on screenshot?

**Comment by Enotmd** [comment]
> @Enotmd why it looks so strange on screenshot?

I just zoomed it out too much.

**Comment by web7evgheni** [comment]
@Enotmd Switched task to you, because construct pages from components is your part of work.

**Comment by Enotmd** [comment]
@web7evgheni  Please review the About page and let me know ifchanges are required.

**Comment by web7evgheni** [comment]
@Enotmd Is ok to make review tomorrow?

**Comment by Enotmd** [comment]
> @Enotmd Is ok to make review tomorrow?

@web7evgheni No problem from my side.  Meanwhile i will be switching to another page.
