### ISSUE TITLE
ContentBanner component for About Page

### ISSUE THREAD

**Issue by Enotmd** [web-seven/website#55]
## Issue: 
Create ContentBanner

## Issue summary:
Required to create ContentBanner component  to display content using style from next screenshot:
![image](https://github.com/web-seven/website/assets/109219657/1dd611cf-d005-4f75-a9ec-4f4590177c0e)
![image](https://github.com/web-seven/website/assets/109219657/364382f5-7f97-48eb-b64e-c604b08151c9)

## References:
 - Link to page with HTML for this component  from local source : MARTEX/HTML/about.html

**Comment by web7evgheni** [comment]
@Enotmd Please name it different. component shall be named by provided functionality, not where it will be used.
