### ISSUE TITLE
Create TwoColumnsText Component 

### ISSUE THREAD

**Issue by Enotmd** [web-seven/website#56]
## Issue: 
Create TwoColumnsText Component 

## Issue summary:
Required to create TwoColumnsText  component  to display content using style from next screenshot:

![image](https://github.com/web-seven/website/assets/109219657/6094eb07-f6ac-43ed-b5c2-5bd1203cfd85)

## References:
 - Link to page with HTML for this component  from local source : MARTEX/HTML/about.html

**Comment by web7evgheni** [comment]
@Enotmd I think better to name it like TwoColumnsText.

**Comment by Enotmd** [comment]
> @Enotmd I think better to name it like TwoColumnsText.

OK, will do. Thanks.
