### ISSUE TITLE
Create ChooseUs component 

### ISSUE THREAD

**Issue by Enotmd** [web-seven/website#57]
## Issue: 
Create ChooseUs component 

## Issue summary:
Required to create ChooseUs component    to display content using style from next screenshot:

![image](https://github.com/web-seven/website/assets/109219657/bee71005-ad41-4e28-a5e6-6a60237b8446)

## References:
 - Link to page with HTML for this component  from local source : MARTEX/HTML/about.html

**Comment by web7evgheni** [comment]
@Enotmd I same like Strategies, but with right side image, i think better to make single component with multiple switchers.

**Comment by Enotmd** [comment]
@BurlacuLucian  Reverse version of  this component https://github.com/web-seven/website/issues/58
