### ISSUE TITLE
ContentCard Component

### ISSUE THREAD

**Issue by Enotmd** [web-seven/website#58]
## Issue: 
Create ContentCard component 

## Issue summary:
Required to create ContentCard component    to display content using style from next screenshot:

![image](https://github.com/web-seven/website/assets/109219657/ba7e64ef-191f-431f-9cda-f69626a9e179)

## References:
 - Link to page with HTML for this component  from local source : MARTEX/HTML/about.html

**Comment by web7evgheni** [comment]
@Enotmd Please do not name is Strategies, because it could be used not just for strategies, think about new abstract name.
