### ISSUE TITLE
Careers page

### ISSUE THREAD

**Issue by Enotmd** [web-seven/website#76]
# issue :
 Careers page

# issue details : 
Create static page for Careers from existing components and add content

**Comment by web7evgheni** [comment]
@Enotmd Please fix issues from screenshot:
![screenshot-develop web7 md-2023 12 18-15_53_29](https://github.com/web-seven/website/assets/810573/4172d108-c544-48e3-83f8-c8fa31346161)

**Comment by web7evgheni** [comment]
@Enotmd Please make careers@web7.md button to have link to "mailto:careers@web7.md"
